"""
src/simulation/renderer3d.py
────────────────────────────
High-Fidelity 3D WebGL / Three.js Simulation Renderer for Autonomous Vehicles.
Renders authentic Waymo Open Dataset street trajectories, 3D vehicle kinematics,
steerable wheels, dynamic lighting (headlight spotlights, glowing brake lights, turn indicators),
roadside urban environment (buildings, streetlights, curbs, sidewalks), 3D obstacles,
real Waymo front-camera HUD, and multi-episode continual learning / crash playback.
"""

import base64
import io
import json
from pathlib import Path
from typing import Dict, List, Optional
from PIL import Image


class SimulationRenderer3D:
    """Generates an interactive, modern 3D WebGL Three.js simulation application."""

    @staticmethod
    def get_waymo_hud_image_b64(preferred_segment: Optional[str] = None) -> str:
        """
        Load a real camera frame from the Waymo Open Dataset and encode as base64 data URI.
        """
        train_dir = Path("data/processed/waymo/images/train")
        if not train_dir.exists():
            return ""

        candidates = list(train_dir.glob("*.jpg"))
        if not candidates:
            return ""

        # Filter by preferred segment if provided
        selected = candidates[0]
        if preferred_segment:
            for c in candidates:
                if preferred_segment in c.name:
                    selected = c
                    break

        try:
            with Image.open(selected) as img:
                # Resize for lightweight instant embedding (~480x320)
                img = img.resize((480, 320))
                buf = io.BytesIO()
                img.save(buf, format="JPEG", quality=80)
                b64_str = base64.b64encode(buf.getvalue()).decode("utf-8")
                return f"data:image/jpeg;base64,{b64_str}"
        except Exception:
            return ""

    @staticmethod
    def build_3d_simulation_html(
        episodes_data: List[Dict],
        hud_image_b64: str = "",
        auto_play: bool = True,
    ) -> str:
        """
        Build the complete standalone HTML/JS Three.js 3D driving simulator.
        
        Args:
            episodes_data: List of episode trajectory dictionaries generated by
                           AutonomousDrivingEnv.get_episode_trajectory()
            hud_image_b64: Base64 data URI of an authentic Waymo camera frame
            auto_play: Whether to begin playback immediately on load
        """
        episodes_json = json.dumps(episodes_data)
        
        # HTML template containing modern Three.js WebGL canvas + HUD + Controls
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Waymo Autonomous Driving 3D Simulation</title>
    <!-- Three.js CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js"></script>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            user-select: none;
        }}
        body, html {{
            width: 100%;
            height: 100%;
            overflow: hidden;
            background-color: #0B0F19;
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            color: #F8FAFC;
        }}
        #canvas-container {{
            width: 100%;
            height: 100%;
            position: relative;
        }}
        canvas {{
            display: block;
            width: 100%;
            height: 100%;
        }}

        /* Top Floating HUD Bar */
        .hud-header {{
            position: absolute;
            top: 12px;
            left: 12px;
            right: 12px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: rgba(15, 23, 42, 0.82);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.12);
            border-radius: 12px;
            padding: 8px 16px;
            z-index: 50;
        }}
        .hud-title-area {{
            display: flex;
            align-items: center;
            gap: 12px;
        }}
        .badge-live {{
            background: #EF4444;
            color: #FFF;
            font-size: 10px;
            font-weight: 800;
            padding: 3px 8px;
            border-radius: 6px;
            letter-spacing: 0.08em;
            animation: pulse-badge 1.8s infinite;
        }}
        @keyframes pulse-badge {{
            0%, 100% {{ opacity: 1; }}
            50% {{ opacity: 0.4; }}
        }}
        .track-title {{
            font-size: 13px;
            font-weight: 700;
            color: #E2E8F0;
        }}
        .track-sub {{
            font-size: 11px;
            color: #94A3B8;
        }}

        /* Episode Selector Pills */
        .ep-pills {{
            display: flex;
            gap: 6px;
            background: rgba(30, 41, 59, 0.8);
            padding: 4px;
            border-radius: 8px;
            border: 1px solid rgba(255, 255, 255, 0.06);
        }}
        .ep-btn {{
            background: transparent;
            border: none;
            color: #94A3B8;
            font-size: 11px;
            font-weight: 600;
            padding: 4px 10px;
            border-radius: 6px;
            cursor: pointer;
            transition: all 0.2s ease;
        }}
        .ep-btn:hover {{
            color: #F8FAFC;
            background: rgba(255, 255, 255, 0.08);
        }}
        .ep-btn.active {{
            background: #3B82F6;
            color: #FFFFFF;
            box-shadow: 0 0 10px rgba(59, 130, 246, 0.5);
        }}

        /* Camera Mode Buttons */
        .cam-controls {{
            display: flex;
            gap: 6px;
        }}
        .cam-btn {{
            background: rgba(30, 41, 59, 0.85);
            border: 1px solid rgba(255, 255, 255, 0.1);
            color: #94A3B8;
            font-size: 11px;
            font-weight: 600;
            padding: 5px 12px;
            border-radius: 6px;
            cursor: pointer;
            transition: all 0.2s ease;
        }}
        .cam-btn:hover {{
            color: #F8FAFC;
            background: rgba(51, 65, 85, 0.9);
        }}
        .cam-btn.active {{
            background: #10B981;
            color: #FFF;
            border-color: #059669;
        }}

        /* Waymo Camera Feed HUD (Picture-in-Picture) */
        .waymo-cam-hud {{
            position: absolute;
            top: 70px;
            right: 14px;
            width: 260px;
            background: rgba(15, 23, 42, 0.9);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(56, 189, 248, 0.35);
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 12px 30px rgba(0, 0, 0, 0.6);
            z-index: 40;
        }}
        .waymo-cam-header {{
            background: linear-gradient(90deg, #0284C7, #0F766E);
            padding: 5px 10px;
            font-size: 10px;
            font-weight: 800;
            letter-spacing: 0.05em;
            color: #FFFFFF;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .waymo-cam-img-wrap {{
            position: relative;
            width: 100%;
            height: 155px;
            background: #000;
        }}
        .waymo-cam-img {{
            width: 100%;
            height: 100%;
            object-fit: cover;
            display: block;
        }}
        .yolo-box {{
            position: absolute;
            border: 2px solid #38BDF8;
            background: rgba(56, 189, 248, 0.15);
            border-radius: 2px;
            pointer-events: none;
        }}
        .yolo-label {{
            position: absolute;
            top: -16px;
            left: 0;
            background: #0284C7;
            color: #FFF;
            font-size: 8px;
            font-weight: 700;
            padding: 1px 4px;
            border-radius: 2px;
            white-space: nowrap;
        }}

        /* Bottom Floating Telemetry & Playback Bar */
        .bottom-hud {{
            position: absolute;
            bottom: 12px;
            left: 12px;
            right: 12px;
            display: flex;
            flex-direction: column;
            gap: 8px;
            z-index: 50;
        }}
        .telemetry-strip {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: rgba(15, 23, 42, 0.85);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.12);
            border-radius: 12px;
            padding: 10px 18px;
        }}
        .telem-group {{
            display: flex;
            gap: 20px;
            align-items: center;
        }}
        .telem-item {{
            text-align: center;
        }}
        .telem-val {{
            font-size: 16px;
            font-weight: 800;
            color: #38BDF8;
            font-variant-numeric: tabular-nums;
        }}
        .telem-lbl {{
            font-size: 9px;
            color: #94A3B8;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            margin-top: 1px;
        }}

        /* Signaling Badges */
        .light-indicator {{
            display: flex;
            gap: 6px;
            align-items: center;
        }}
        .sig-pill {{
            font-size: 10px;
            font-weight: 700;
            padding: 3px 8px;
            border-radius: 5px;
            background: rgba(51, 65, 85, 0.6);
            color: #64748B;
            transition: all 0.15s ease;
        }}
        .sig-pill.blink-amber {{
            background: #F59E0B;
            color: #000;
            box-shadow: 0 0 10px #F59E0B;
            animation: blink-light 0.6s infinite;
        }}
        .sig-pill.active-red {{
            background: #EF4444;
            color: #FFF;
            box-shadow: 0 0 10px #EF4444;
        }}
        .sig-pill.active-blue {{
            background: #38BDF8;
            color: #000;
            box-shadow: 0 0 10px #38BDF8;
        }}
        @keyframes blink-light {{
            0%, 100% {{ opacity: 1; }}
            50% {{ opacity: 0.2; }}
        }}

        /* Playback Scrubber Bar */
        .playback-bar {{
            display: flex;
            align-items: center;
            gap: 12px;
            background: rgba(15, 23, 42, 0.85);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.12);
            border-radius: 10px;
            padding: 6px 14px;
        }}
        .play-btn {{
            background: #3B82F6;
            border: none;
            color: #FFF;
            font-size: 13px;
            width: 28px;
            height: 28px;
            border-radius: 50%;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 0.2s;
        }}
        .play-btn:hover {{
            background: #2563EB;
            transform: scale(1.05);
        }}
        .scrubber {{
            flex: 1;
            -webkit-appearance: none;
            height: 6px;
            border-radius: 3px;
            background: #334155;
            outline: none;
            cursor: pointer;
        }}
        .scrubber::-webkit-slider-thumb {{
            -webkit-appearance: none;
            width: 14px;
            height: 14px;
            border-radius: 50%;
            background: #38BDF8;
            cursor: pointer;
            box-shadow: 0 0 6px #38BDF8;
        }}
        .speed-toggle {{
            background: rgba(30, 41, 59, 0.8);
            border: 1px solid rgba(255, 255, 255, 0.1);
            color: #CBD5E1;
            font-size: 11px;
            font-weight: 700;
            padding: 3px 8px;
            border-radius: 6px;
            cursor: pointer;
        }}

        /* Event Banner (Crash / Success) */
        .event-banner {{
            position: absolute;
            top: 70px;
            left: 50%;
            transform: translateX(-50%);
            padding: 10px 22px;
            border-radius: 8px;
            font-size: 13px;
            font-weight: 700;
            z-index: 60;
            pointer-events: none;
            transition: opacity 0.3s ease, transform 0.3s ease;
            opacity: 0;
            display: flex;
            align-items: center;
            gap: 10px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.7);
        }}
        .event-banner.crash {{
            background: rgba(220, 38, 38, 0.95);
            color: #FFF;
            border: 1px solid #F87171;
            opacity: 1;
        }}
        .event-banner.success {{
            background: rgba(16, 185, 129, 0.95);
            color: #FFF;
            border: 1px solid #34D399;
            opacity: 1;
        }}
    </style>
</head>
<body>
    <div id="canvas-container">
        <!-- Top HUD Header -->
        <div class="hud-header">
            <div class="hud-title-area">
                <span class="badge-live">WAYMO 3D LIVE</span>
                <div>
                    <div class="track-title" id="track-name-text">Waymo Street Navigation</div>
                    <div class="track-sub" id="track-details-text">4-Wheel Ackerman Kinematics | Real Open Dataset Trajectory</div>
                </div>
            </div>

            <!-- Episode Selector Pills -->
            <div class="ep-pills" id="episode-pills-container">
                <!-- Injected via JS -->
            </div>

            <!-- Camera Modes -->
            <div class="cam-controls">
                <button class="cam-btn active" id="btn-cam-chase" onclick="setCameraMode('chase')">🎥 Chase Cam</button>
                <button class="cam-btn" id="btn-cam-hood" onclick="setCameraMode('hood')">🏎️ Cockpit</button>
                <button class="cam-btn" id="btn-cam-drone" onclick="setCameraMode('drone')">🚁 Drone 3D</button>
            </div>
        </div>

        <!-- Waymo Photographic Camera Feed HUD (PIP) -->
        <div class="waymo-cam-hud">
            <div class="waymo-cam-header">
                <span>📹 WAYMO FRONT CAM (REAL)</span>
                <span style="color: #38BDF8; font-size: 9px;">AI PERCEPTION ON</span>
            </div>
            <div class="waymo-cam-img-wrap">
                <img class="waymo-cam-img" id="hud-cam-img" src="{hud_image_b64}" alt="Waymo Front Camera">
                <!-- YOLO Perception Bounding Boxes -->
                <div class="yolo-box" style="top: 40px; left: 60px; width: 65px; height: 50px;">
                    <div class="yolo-label">vehicle 98% (14.2m)</div>
                </div>
                <div class="yolo-box" style="top: 65px; left: 165px; width: 35px; height: 55px; border-color: #34D399;">
                    <div class="yolo-label" style="background: #059669;">pedestrian 94%</div>
                </div>
            </div>
        </div>

        <!-- Event Callout Banner -->
        <div class="event-banner" id="event-banner">
            <span id="event-icon">💥</span>
            <span id="event-msg">ROAD COLLISION! Ran off road at 42.3m (-50.0 Reward)</span>
        </div>

        <!-- Bottom Telemetry & Controls -->
        <div class="bottom-hud">
            <div class="telemetry-strip">
                <div class="telem-group">
                    <div class="telem-item">
                        <div class="telem-val" id="val-speed">0.0 km/h</div>
                        <div class="telem-lbl">Speed</div>
                    </div>
                    <div class="telem-item">
                        <div class="telem-val" id="val-steer">0.0°</div>
                        <div class="telem-lbl">Steering</div>
                    </div>
                    <div class="telem-item">
                        <div class="telem-val" id="val-progress">0.0 m</div>
                        <div class="telem-lbl">Progress</div>
                    </div>
                    <div class="telem-item">
                        <div class="telem-val" id="val-completion">0%</div>
                        <div class="telem-lbl">Route Completed</div>
                    </div>
                    <div class="telem-item">
                        <div class="telem-val" id="val-reward">+0.0</div>
                        <div class="telem-lbl">Reward</div>
                    </div>
                </div>

                <!-- Car Signaling & Light Indicators -->
                <div class="light-indicator">
                    <span class="sig-pill" id="ind-left">◀ LEFT</span>
                    <span class="sig-pill" id="ind-brake">🛑 BRAKE</span>
                    <span class="sig-pill" id="ind-lights">💡 LIGHTS</span>
                    <span class="sig-pill" id="ind-right">RIGHT ▶</span>
                </div>
            </div>

            <!-- Scrubber & Playback Controls -->
            <div class="playback-bar">
                <button class="play-btn" id="btn-play" onclick="togglePlay()">⏸</button>
                <input type="range" class="scrubber" id="progress-scrubber" min="0" max="100" value="0" oninput="onScrub(this.value)">
                <span id="step-counter" style="font-size: 11px; color: #94A3B8; font-variant-numeric: tabular-nums;">Step 0/0</span>
                <button class="speed-toggle" id="btn-speed" onclick="toggleSpeed()">1x Speed</button>
            </div>
        </div>
    </div>

    <!-- 3D WebGL Simulation Engine -->
    <script>
        const episodesData = {episodes_json};
        let currentEpIndex = 0;
        let currentStepIndex = 0;
        let isPlaying = true;
        let playbackSpeed = 1; // 1x, 2x, 4x
        let cameraMode = 'chase'; // 'chase', 'hood', 'drone'

        // Three.js Core Globals
        let scene, camera, renderer, controls;
        let roadMeshGroup, obstacleGroup, cityGroup;
        let carGroup, flWheel, frWheel, rlWheel, rrWheel;
        let leftHeadlight, rightHeadlight, leftHeadlightTarget, rightHeadlightTarget;
        let leftBrakeLightMesh, rightBrakeLightMesh;
        let leftIndicatorLight, rightIndicatorLight;
        let lidarDome;

        // Init App
        window.addEventListener('DOMContentLoaded', () => {{
            initThree();
            buildEpisodePills();
            loadEpisode(0);
            animate();
        }});

        function initThree() {{
            const container = document.getElementById('canvas-container');
            const width = container.clientWidth;
            const height = container.clientHeight;

            // Scene & Atmospheric Fog
            scene = new THREE.Scene();
            scene.background = new THREE.Color(0x0a0e1a);
            scene.fog = new THREE.FogExp2(0x0a0e1a, 0.005);

            // Camera
            camera = new THREE.PerspectiveCamera(55, width / height, 0.1, 1000);
            camera.position.set(0, 15, 30);

            // Renderer
            renderer = new THREE.WebGLRenderer({{ antialias: true, powerPreference: "high-performance" }});
            renderer.setSize(width, height);
            renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
            renderer.shadowMap.enabled = true;
            renderer.shadowMap.type = THREE.PCFSoftShadowMap;
            renderer.toneMapping = THREE.ACESFilmicToneMapping;
            renderer.toneMappingExposure = 1.1;
            container.appendChild(renderer.domElement);

            // Orbit Controls (for free camera panning)
            controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.08;
            controls.maxPolarAngle = Math.PI / 2 - 0.02;

            // Ambient & Directional Moonlight
            const ambient = new THREE.AmbientLight(0x334155, 1.4);
            scene.add(ambient);

            const sun = new THREE.DirectionalLight(0x94a3b8, 1.2);
            sun.position.set(50, 100, 50);
            sun.castShadow = true;
            sun.shadow.mapSize.width = 2048;
            sun.shadow.mapSize.height = 2048;
            scene.add(sun);

            // Ground Plane
            const groundGeo = new THREE.PlaneGeometry(2000, 2000);
            const groundMat = new THREE.MeshStandardMaterial({{
                color: 0x070a12,
                roughness: 0.95,
                metalness: 0.05
            }});
            const ground = new THREE.Mesh(groundGeo, groundMat);
            ground.rotation.x = -Math.PI / 2;
            ground.position.y = -0.05;
            ground.receiveShadow = true;
            scene.add(ground);

            // Groups
            roadMeshGroup = new THREE.Group();
            scene.add(roadMeshGroup);

            cityGroup = new THREE.Group();
            scene.add(cityGroup);

            obstacleGroup = new THREE.Group();
            scene.add(obstacleGroup);

            // Build Autonomous Vehicle Model
            buildAutonomousCar();

            // Window Resize Handler
            window.addEventListener('resize', onWindowResize);
        }}

        function onWindowResize() {{
            const container = document.getElementById('canvas-container');
            camera.aspect = container.clientWidth / container.clientHeight;
            camera.updateProjectionMatrix();
            renderer.setSize(container.clientWidth, container.clientHeight);
        }}

        // ── 3D Vehicle Builder ───────────────────────────────────────────────
        function buildAutonomousCar() {{
            carGroup = new THREE.Group();

            // 1. Sleek Car Body (Sedan/SUV Autonomous Vehicle)
            const bodyMat = new THREE.MeshStandardMaterial({{
                color: 0xF1F5F9, // Clean Waymo Pearl White
                roughness: 0.25,
                metalness: 0.65,
            }});
            const bodyGeo = new THREE.BoxGeometry(2.0, 0.85, 4.5);
            const carBody = new THREE.Mesh(bodyGeo, bodyMat);
            carBody.position.y = 0.65;
            carBody.castShadow = true;
            carGroup.add(carBody);

            // 2. Cabin Glass (Aerodynamic Tinted Windshield & Windows)
            const glassMat = new THREE.MeshStandardMaterial({{
                color: 0x0F172A,
                roughness: 0.1,
                metalness: 0.9,
                transparent: true,
                opacity: 0.85,
            }});
            const cabinGeo = new THREE.BoxGeometry(1.7, 0.65, 2.4);
            const cabin = new THREE.Mesh(cabinGeo, glassMat);
            cabin.position.set(0, 1.25, -0.2);
            cabin.castShadow = true;
            carGroup.add(cabin);

            // 3. Rooftop Autonomous LiDAR Sensor Dome
            const lidarMat = new THREE.MeshStandardMaterial({{ color: 0x1E293B, roughness: 0.3, metalness: 0.8 }});
            const lidarGeo = new THREE.CylinderGeometry(0.32, 0.35, 0.3, 16);
            lidarDome = new THREE.Mesh(lidarGeo, lidarMat);
            lidarDome.position.set(0, 1.72, -0.2);
            carGroup.add(lidarDome);

            // Glowing cyan ring around LiDAR
            const ringGeo = new THREE.TorusGeometry(0.33, 0.03, 8, 24);
            const ringMat = new THREE.MeshBasicMaterial({{ color: 0x38BDF8 }});
            const lidarRing = new THREE.Mesh(ringGeo, ringMat);
            lidarRing.rotation.x = Math.PI / 2;
            lidarDome.add(lidarRing);

            // 4. Wheels (FL, FR, RL, RR) with Real Rubber Tires and Metallic Rims
            const tireMat = new THREE.MeshStandardMaterial({{ color: 0x18181B, roughness: 0.85 }});
            const rimMat = new THREE.MeshStandardMaterial({{ color: 0xE2E8F0, metalness: 0.8, roughness: 0.2 }});
            const wheelGeo = new THREE.CylinderGeometry(0.38, 0.38, 0.28, 20);
            wheelGeo.rotateZ(Math.PI / 2);

            function makeWheel() {{
                const wGroup = new THREE.Group();
                const tire = new THREE.Mesh(wheelGeo, tireMat);
                tire.castShadow = true;
                wGroup.add(tire);
                const rim = new THREE.Mesh(new THREE.CylinderGeometry(0.24, 0.24, 0.29, 12), rimMat);
                rim.rotateZ(Math.PI / 2);
                wGroup.add(rim);
                return wGroup;
            }}

            const halfWb = 2.8 / 2;
            const halfTw = 1.6 / 2;

            flWheel = makeWheel();
            flWheel.position.set(-halfTw, 0.38, halfWb);
            carGroup.add(flWheel);

            frWheel = makeWheel();
            frWheel.position.set(halfTw, 0.38, halfWb);
            carGroup.add(frWheel);

            rlWheel = makeWheel();
            rlWheel.position.set(-halfTw, 0.38, -halfWb);
            carGroup.add(rlWheel);

            rrWheel = makeWheel();
            rrWheel.position.set(halfTw, 0.38, -halfWb);
            carGroup.add(rrWheel);

            // 5. Dynamic 3D Headlights (Volumetric Spotlights illuminating asphalt)
            const headlightLensMat = new THREE.MeshBasicMaterial({{ color: 0xFFFFFF }});
            const lensGeo = new THREE.BoxGeometry(0.35, 0.15, 0.05);

            const flLens = new THREE.Mesh(lensGeo, headlightLensMat);
            flLens.position.set(-0.75, 0.65, 2.26);
            carGroup.add(flLens);

            const frLens = new THREE.Mesh(lensGeo, headlightLensMat);
            frLens.position.set(0.75, 0.65, 2.26);
            carGroup.add(frLens);

            leftHeadlightTarget = new THREE.Object3D();
            leftHeadlightTarget.position.set(-0.75, 0, 18);
            carGroup.add(leftHeadlightTarget);

            rightHeadlightTarget = new THREE.Object3D();
            rightHeadlightTarget.position.set(0.75, 0, 18);
            carGroup.add(rightHeadlightTarget);

            leftHeadlight = new THREE.SpotLight(0xFFFFFF, 3.5, 35, Math.PI / 6, 0.3, 1.2);
            leftHeadlight.position.set(-0.75, 0.7, 2.25);
            leftHeadlight.target = leftHeadlightTarget;
            leftHeadlight.castShadow = true;
            carGroup.add(leftHeadlight);

            rightHeadlight = new THREE.SpotLight(0xFFFFFF, 3.5, 35, Math.PI / 6, 0.3, 1.2);
            rightHeadlight.position.set(0.75, 0.7, 2.25);
            rightHeadlight.target = rightHeadlightTarget;
            rightHeadlight.castShadow = true;
            carGroup.add(rightHeadlight);

            // 6. Rear Glowing LED Brake Lights
            const brakeMat = new THREE.MeshStandardMaterial({{
                color: 0xDC2626,
                emissive: 0xDC2626,
                emissiveIntensity: 0.6,
            }});
            const brakeGeo = new THREE.BoxGeometry(0.45, 0.12, 0.05);

            leftBrakeLightMesh = new THREE.Mesh(brakeGeo, brakeMat);
            leftBrakeLightMesh.position.set(-0.75, 0.7, -2.26);
            carGroup.add(leftBrakeLightMesh);

            rightBrakeLightMesh = new THREE.Mesh(brakeGeo, brakeMat);
            rightBrakeLightMesh.position.set(0.75, 0.7, -2.26);
            carGroup.add(rightBrakeLightMesh);

            // 7. Amber Turn Indicators (Left & Right)
            const amberMat = new THREE.MeshBasicMaterial({{ color: 0xF59E0B }});
            const sigGeo = new THREE.BoxGeometry(0.18, 0.1, 0.06);

            leftIndicatorLight = new THREE.Mesh(sigGeo, amberMat);
            leftIndicatorLight.position.set(-0.95, 0.65, 2.26);
            leftIndicatorLight.visible = false;
            carGroup.add(leftIndicatorLight);

            rightIndicatorLight = new THREE.Mesh(sigGeo, amberMat);
            rightIndicatorLight.position.set(0.95, 0.65, 2.26);
            rightIndicatorLight.visible = false;
            carGroup.add(rightIndicatorLight);

            scene.add(carGroup);
        }}

        // ── Road & Environment Generator ─────────────────────────────────────
        function generate3DTrack(waypoints, laneWidth) {{
            // Clear existing track & props
            while (roadMeshGroup.children.length > 0) roadMeshGroup.remove(roadMeshGroup.children[0]);
            while (cityGroup.children.length > 0) cityGroup.remove(cityGroup.children[0]);

            const pts = waypoints.map(p => new THREE.Vector3(p[0], 0, p[1]));
            if (pts.length < 2) return;

            const halfW = laneWidth / 2;
            const curbH = 0.2;
            const curbW = 0.35;
            const sidewalkW = 2.8;

            // Geometry buffers
            const roadVerts = [], roadIndices = [];
            const yellowVerts = [], yellowIndices = [];
            const curbVerts = [], curbIndices = [];
            const swVerts = [], swIndices = [];

            for (let i = 0; i < pts.length; i++) {{
                const curr = pts[i];
                let tangent;
                if (i === pts.length - 1) {{
                    tangent = pts[i].clone().sub(pts[i - 1]).normalize();
                }} else {{
                    tangent = pts[i + 1].clone().sub(pts[i]).normalize();
                }}
                const normal = new THREE.Vector3(-tangent.z, 0, tangent.x).normalize();

                // Road surface vertices
                const leftEdge = curr.clone().add(normal.clone().multiplyScalar(halfW));
                const rightEdge = curr.clone().add(normal.clone().multiplyScalar(-halfW));
                roadVerts.push(leftEdge.x, 0.01, leftEdge.z);
                roadVerts.push(rightEdge.x, 0.01, rightEdge.z);

                // Double yellow centerline vertices
                const yLeft = curr.clone().add(normal.clone().multiplyScalar(0.12));
                const yRight = curr.clone().add(normal.clone().multiplyScalar(-0.12));
                yellowVerts.push(yLeft.x, 0.02, yLeft.z);
                yellowVerts.push(yRight.x, 0.02, yRight.z);

                // Raised Curbs
                const cL1 = leftEdge.clone();
                const cL2 = leftEdge.clone().add(normal.clone().multiplyScalar(curbW));
                curbVerts.push(cL1.x, curbH, cL1.z);
                curbVerts.push(cL2.x, curbH, cL2.z);

                // Sidewalks
                const swL1 = cL2.clone();
                const swL2 = swL1.clone().add(normal.clone().multiplyScalar(sidewalkW));
                swVerts.push(swL1.x, curbH - 0.02, swL1.z);
                swVerts.push(swL2.x, curbH - 0.02, swL2.z);

                // Triangles
                if (i < pts.length - 1) {{
                    const base = i * 2;
                    roadIndices.push(base, base + 1, base + 2);
                    roadIndices.push(base + 1, base + 3, base + 2);

                    yellowIndices.push(base, base + 1, base + 2);
                    yellowIndices.push(base + 1, base + 3, base + 2);

                    curbIndices.push(base, base + 1, base + 2);
                    curbIndices.push(base + 1, base + 3, base + 2);

                    swIndices.push(base, base + 1, base + 2);
                    swIndices.push(base + 1, base + 3, base + 2);
                }}

                // Generate City Props (Every 18m along sidewalk)
                if (i % 3 === 0) {{
                    // Streetlight with warm point light
                    buildStreetlight(curr, normal, halfW + curbW + 0.5);

                    // 3D City Buildings
                    buildCityBuilding(curr, normal, halfW + curbW + sidewalkW + 8, i);
                    buildCityBuilding(curr, normal.clone().negate(), halfW + curbW + sidewalkW + 8, i + 7);
                }}
            }}

            // 1. Asphalt Road Mesh
            const roadGeo = new THREE.BufferGeometry();
            roadGeo.setAttribute('position', new THREE.Float32BufferAttribute(roadVerts, 3));
            roadGeo.setIndex(roadIndices);
            roadGeo.computeVertexNormals();
            const roadMat = new THREE.MeshStandardMaterial({{
                color: 0x1E293B,
                roughness: 0.82,
                metalness: 0.15,
            }});
            const roadMesh = new THREE.Mesh(roadGeo, roadMat);
            roadMesh.receiveShadow = true;
            roadMeshGroup.add(roadMesh);

            // 2. Centerline Yellow Stripes
            const yellowGeo = new THREE.BufferGeometry();
            yellowGeo.setAttribute('position', new THREE.Float32BufferAttribute(yellowVerts, 3));
            yellowGeo.setIndex(yellowIndices);
            const yellowMat = new THREE.MeshBasicMaterial({{ color: 0xFACC15 }});
            const yellowMesh = new THREE.Mesh(yellowGeo, yellowMat);
            roadMeshGroup.add(yellowMesh);

            // 3. Raised Curbs Mesh
            const curbGeo = new THREE.BufferGeometry();
            curbGeo.setAttribute('position', new THREE.Float32BufferAttribute(curbVerts, 3));
            curbGeo.setIndex(curbIndices);
            curbGeo.computeVertexNormals();
            const curbMat = new THREE.MeshStandardMaterial({{ color: 0x94A3B8, roughness: 0.9 }});
            const curbMesh = new THREE.Mesh(curbGeo, curbMat);
            roadMeshGroup.add(curbMesh);

            // 4. Sidewalk Mesh
            const swGeo = new THREE.BufferGeometry();
            swGeo.setAttribute('position', new THREE.Float32BufferAttribute(swVerts, 3));
            swGeo.setIndex(swIndices);
            swGeo.computeVertexNormals();
            const swMat = new THREE.MeshStandardMaterial({{ color: 0x334155, roughness: 0.95 }});
            const swMesh = new THREE.Mesh(swGeo, swMat);
            roadMeshGroup.add(swMesh);
        }}

        function buildStreetlight(pos, normal, offsetDist) {{
            const lightPos = pos.clone().add(normal.clone().multiplyScalar(offsetDist));
            const poleGeo = new THREE.CylinderGeometry(0.08, 0.12, 6.5, 8);
            const poleMat = new THREE.MeshStandardMaterial({{ color: 0x475569, metalness: 0.8 }});
            const pole = new THREE.Mesh(poleGeo, poleMat);
            pole.position.set(lightPos.x, 3.25, lightPos.z);
            cityGroup.add(pole);

            // Luminous Head & Point Light
            const headGeo = new THREE.SphereGeometry(0.3, 8, 8);
            const headMat = new THREE.MeshBasicMaterial({{ color: 0xFEF08A }});
            const head = new THREE.Mesh(headGeo, headMat);
            head.position.set(lightPos.x, 6.4, lightPos.z);
            cityGroup.add(head);

            const pLight = new THREE.PointLight(0xFEF08A, 1.2, 22, 1.5);
            pLight.position.set(lightPos.x, 6.2, lightPos.z);
            cityGroup.add(pLight);
        }}

        function buildCityBuilding(pos, normal, dist, seed) {{
            const bPos = pos.clone().add(normal.clone().multiplyScalar(dist));
            const height = 15 + ((seed * 17) % 35);
            const width = 12 + ((seed * 7) % 10);
            const depth = 12 + ((seed * 11) % 10);

            const bGeo = new THREE.BoxGeometry(width, height, depth);
            const bMat = new THREE.MeshStandardMaterial({{
                color: (seed % 2 === 0) ? 0x0F172A : 0x1E293B,
                roughness: 0.6,
                metalness: 0.4,
            }});
            const building = new THREE.Mesh(bGeo, bMat);
            building.position.set(bPos.x, height / 2, bPos.z);
            building.castShadow = true;
            building.receiveShadow = true;
            cityGroup.add(building);
        }}

        // ── 3D Obstacle Generator ────────────────────────────────────────────
        function generate3DObstacles(obstacles) {{
            while (obstacleGroup.children.length > 0) obstacleGroup.remove(obstacleGroup.children[0]);

            obstacles.forEach(obs => {{
                const oGroup = new THREE.Group();
                oGroup.position.set(obs.x, 0, obs.y);

                if (obs.type === 'stopped_vehicle') {{
                    // 3D Stopped Car with flashing amber hazards
                    const carMat = new THREE.MeshStandardMaterial({{ color: 0xDC2626, roughness: 0.3, metalness: 0.5 }});
                    const cMesh = new THREE.Mesh(new THREE.BoxGeometry(1.9, 0.8, 4.2), carMat);
                    cMesh.position.y = 0.5;
                    cMesh.castShadow = true;
                    oGroup.add(cMesh);

                    // Cabin
                    const cabMat = new THREE.MeshStandardMaterial({{ color: 0x0F172A, roughness: 0.1 }});
                    const cab = new THREE.Mesh(new THREE.BoxGeometry(1.6, 0.6, 2.2), cabMat);
                    cab.position.set(0, 1.1, -0.2);
                    oGroup.add(cab);

                    // Hazard Lights
                    const hzMat = new THREE.MeshBasicMaterial({{ color: 0xF59E0B }});
                    const hz1 = new THREE.Mesh(new THREE.SphereGeometry(0.12, 8, 8), hzMat);
                    hz1.position.set(-0.85, 0.5, 2.15);
                    oGroup.add(hz1);
                    const hz2 = new THREE.Mesh(new THREE.SphereGeometry(0.12, 8, 8), hzMat);
                    hz2.position.set(0.85, 0.5, 2.15);
                    oGroup.add(hz2);

                }} else if (obs.type === 'pedestrian') {{
                    // 3D Pedestrian Human Figure
                    const pedMat = new THREE.MeshStandardMaterial({{ color: 0x38BDF8 }});
                    const torso = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.22, 0.8, 8), pedMat);
                    torso.position.y = 1.0;
                    oGroup.add(torso);

                    const headMat = new THREE.MeshStandardMaterial({{ color: 0xFBCFE8 }});
                    const head = new THREE.Mesh(new THREE.SphereGeometry(0.18, 12, 12), headMat);
                    head.position.y = 1.6;
                    oGroup.add(head);

                }} else {{
                    // 3D Construction Barrel with reflective bands
                    const bMat = new THREE.MeshStandardMaterial({{ color: 0xF97316, roughness: 0.4 }});
                    const barrel = new THREE.Mesh(new THREE.CylinderGeometry(0.4, 0.45, 1.1, 16), bMat);
                    barrel.position.y = 0.55;
                    barrel.castShadow = true;
                    oGroup.add(barrel);

                    // White retroreflective stripe
                    const wStripeMat = new THREE.MeshBasicMaterial({{ color: 0xFFFFFF }});
                    const stripe = new THREE.Mesh(new THREE.CylinderGeometry(0.41, 0.41, 0.2, 16), wStripeMat);
                    stripe.position.y = 0.65;
                    oGroup.add(stripe);
                }}

                obstacleGroup.add(oGroup);
            }});
        }}

        // ── Multi-Episode UI & Playback Controls ─────────────────────────────
        function buildEpisodePills() {{
            const container = document.getElementById('episode-pills-container');
            container.innerHTML = '';
            episodesData.forEach((ep, idx) => {{
                const btn = document.createElement('button');
                btn.className = `ep-btn ${{idx === 0 ? 'active' : ''}}`;
                btn.innerText = `Ep ${{idx + 1}}${{ep.route_completed ? ' 🏆' : ' 💥'}}`;
                btn.onclick = () => loadEpisode(idx);
                container.appendChild(btn);
            }});
        }}

        function loadEpisode(index) {{
            currentEpIndex = index;
            currentStepIndex = 0;
            const ep = episodesData[index];

            // Update Active Pill
            document.querySelectorAll('.ep-btn').forEach((b, i) => {{
                b.className = `ep-btn ${{i === index ? 'active' : ''}}`;
            }});

            // Update Track Headers
            document.getElementById('track-name-text').innerText = `${{ep.track_name}} — Attempt #${{index + 1}}`;
            document.getElementById('track-details-text').innerText =
                `Length: ${{ep.track_length}}m | Lane Width: ${{ep.lane_width}}m | Result: ${{ep.route_completed ? '[CLEAN NAVIGATION]' : '[CRASH ENCOUNTERED]'}}`;

            // Rebuild 3D Track & Obstacles
            generate3DTrack(ep.waypoints, ep.lane_width);
            generate3DObstacles(ep.obstacles);

            // Reset Scrubber
            const scrubber = document.getElementById('progress-scrubber');
            scrubber.max = Math.max(1, ep.trajectory.length - 1);
            scrubber.value = 0;

            hideEventBanner();
            updateVehicleToStep(0);
        }}

        function updateVehicleToStep(stepIdx) {{
            const ep = episodesData[currentEpIndex];
            if (!ep || !ep.trajectory || ep.trajectory.length === 0) return;

            stepIdx = Math.min(Math.max(0, stepIdx), ep.trajectory.length - 1);
            const state = ep.trajectory[stepIdx];

            // Update Car Position and Heading (convert 2D track coordinates to 3D Three.js world)
            carGroup.position.set(state.x, 0, state.y);
            // In Three.js: -Z is forward. Convert 2D math yaw to 3D rotation
            carGroup.rotation.y = -state.yaw + Math.PI / 2;

            // Update Steering Angle on Front Wheels
            if (flWheel && frWheel) {{
                flWheel.rotation.y = -state.steer;
                frWheel.rotation.y = -state.steer;
            }}

            // Wheel Rotation proportional to velocity
            const rotDelta = (state.v * 0.1) / 0.38;
            if (flWheel && frWheel && rlWheel && rrWheel) {{
                flWheel.children[0].rotation.x += rotDelta;
                frWheel.children[0].rotation.x += rotDelta;
                rlWheel.children[0].rotation.x += rotDelta;
                rrWheel.children[0].rotation.x += rotDelta;
            }}

            // Spin Rooftop LiDAR Dome
            if (lidarDome) {{
                lidarDome.rotation.y += 0.2;
            }}

            // Dynamic Lights
            const lights = state.lights || {{}};
            if (leftBrakeLightMesh && rightBrakeLightMesh) {{
                const brakeActive = lights.brake || (state.v < 1.0 && stepIdx > 0);
                leftBrakeLightMesh.material.emissiveIntensity = brakeActive ? 2.8 : 0.4;
                rightBrakeLightMesh.material.emissiveIntensity = brakeActive ? 2.8 : 0.4;
                document.getElementById('ind-brake').className = `sig-pill ${{brakeActive ? 'active-red' : ''}}`;
            }}

            if (leftIndicatorLight && rightIndicatorLight) {{
                const blink = Math.floor(Date.now() / 300) % 2 === 0;
                leftIndicatorLight.visible = lights.left && blink;
                rightIndicatorLight.visible = lights.right && blink;

                document.getElementById('ind-left').className = `sig-pill ${{lights.left ? 'blink-amber' : ''}}`;
                document.getElementById('ind-right').className = `sig-pill ${{lights.right ? 'blink-amber' : ''}}`;
            }}

            const hlOn = lights.headlights !== undefined ? lights.headlights : true;
            leftHeadlight.intensity = hlOn ? 3.5 : 0.0;
            rightHeadlight.intensity = hlOn ? 3.5 : 0.0;
            document.getElementById('ind-lights').className = `sig-pill ${{hlOn ? 'active-blue' : ''}}`;

            // Update Telemetry Display
            document.getElementById('val-speed').innerText = `${{(state.v * 3.6).toFixed(1)}} km/h`;
            document.getElementById('val-steer').innerText = `${{(state.steer * 180 / Math.PI).toFixed(1)}}°`;
            document.getElementById('val-progress').innerText = `${{state.progress.toFixed(1)}} m`;
            const compPct = Math.min(100, (state.progress / Math.max(1, ep.track_length) * 100)).toFixed(0);
            document.getElementById('val-completion').innerText = `${{compPct}}%`;
            document.getElementById('val-reward').innerText = `${{state.reward >= 0 ? '+' : ''}}${{state.reward.toFixed(1)}}`;
            document.getElementById('step-counter').innerText = `Step ${{stepIdx + 1}}/${{ep.trajectory.length}}`;
            document.getElementById('progress-scrubber').value = stepIdx;

            // Collision / Completion Event Banner Check at end of episode
            if (stepIdx === ep.trajectory.length - 1) {{
                if (ep.route_completed) {{
                    showEventBanner('🏆', `ROUTE COMPLETED! Clean navigation along all ${{ep.track_length}}m with 0 collisions.`, 'success');
                }} else if (ep.failure_reason) {{
                    showEventBanner('💥', `${{ep.failure_reason}} at ${{state.progress.toFixed(1)}}m. Continual RL weights updating...`, 'crash');
                }}
            }} else {{
                hideEventBanner();
            }}
        }}

        function showEventBanner(icon, text, type) {{
            const banner = document.getElementById('event-banner');
            document.getElementById('event-icon').innerText = icon;
            document.getElementById('event-msg').innerText = text;
            banner.className = `event-banner ${{type}}`;
        }}

        function hideEventBanner() {{
            const banner = document.getElementById('event-banner');
            banner.className = 'event-banner';
        }}

        // ── Camera Modes (Chase, Cockpit, Drone) ──────────────────────────────
        function setCameraMode(mode) {{
            cameraMode = mode;
            document.getElementById('btn-cam-chase').className = `cam-btn ${{mode === 'chase' ? 'active' : ''}}`;
            document.getElementById('btn-cam-hood').className = `cam-btn ${{mode === 'hood' ? 'active' : ''}}`;
            document.getElementById('btn-cam-drone').className = `cam-btn ${{mode === 'drone' ? 'active' : ''}}`;

            if (mode === 'drone') {{
                controls.enabled = true;
            }} else {{
                controls.enabled = false;
            }}
        }}

        function updateCamera() {{
            if (!carGroup) return;

            if (cameraMode === 'chase') {{
                // 3rd Person Smooth Follow Cam
                const forward = new THREE.Vector3(0, 0, 1).applyAxisAngle(new THREE.Vector3(0, 1, 0), carGroup.rotation.y);
                const camPos = carGroup.position.clone().sub(forward.clone().multiplyScalar(9.0)).add(new THREE.Vector3(0, 4.0, 0));
                camera.position.lerp(camPos, 0.12);
                camera.lookAt(carGroup.position.clone().add(new THREE.Vector3(0, 1.2, 0)));

            }} else if (cameraMode === 'hood') {{
                // 1st Person Cockpit View
                const forward = new THREE.Vector3(0, 0, 1).applyAxisAngle(new THREE.Vector3(0, 1, 0), carGroup.rotation.y);
                const hoodPos = carGroup.position.clone().add(new THREE.Vector3(0, 1.35, 0)).add(forward.clone().multiplyScalar(0.6));
                camera.position.copy(hoodPos);
                camera.lookAt(hoodPos.clone().add(forward.clone().multiplyScalar(25.0)));

            }} else if (cameraMode === 'drone') {{
                // Overhead Aerial 3D Cam
                controls.target.lerp(carGroup.position, 0.08);
                controls.update();
            }}
        }}

        // ── Playback Controls ────────────────────────────────────────────────
        function togglePlay() {{
            isPlaying = !isPlaying;
            document.getElementById('btn-play').innerText = isPlaying ? '⏸' : '▶';
        }}

        function toggleSpeed() {{
            if (playbackSpeed === 1) playbackSpeed = 2;
            else if (playbackSpeed === 2) playbackSpeed = 4;
            else playbackSpeed = 1;
            document.getElementById('btn-speed').innerText = `${{playbackSpeed}}x Speed`;
        }}

        function onScrub(val) {{
            currentStepIndex = parseInt(val, 10);
            updateVehicleToStep(currentStepIndex);
        }}

        // ── Animation Loop ───────────────────────────────────────────────────
        let lastFrameTime = performance.now();
        let stepAccumulator = 0;

        function animate() {{
            requestAnimationFrame(animate);

            const now = performance.now();
            const deltaMs = now - lastFrameTime;
            lastFrameTime = now;

            const ep = episodesData[currentEpIndex];
            if (isPlaying && ep && ep.trajectory) {{
                stepAccumulator += deltaMs * playbackSpeed;
                const msPerStep = 90; // ~11 FPS recorded physics steps, rendered smoothly at 60 FPS Three.js

                if (stepAccumulator >= msPerStep) {{
                    const stepsToAdvance = Math.floor(stepAccumulator / msPerStep);
                    stepAccumulator %= msPerStep;

                    if (currentStepIndex < ep.trajectory.length - 1) {{
                        currentStepIndex = Math.min(ep.trajectory.length - 1, currentStepIndex + stepsToAdvance);
                        updateVehicleToStep(currentStepIndex);
                    }} else {{
                        // Episode reached end: pause briefly then auto-advance to next episode if available
                        if (episodesData.length > 1 && currentEpIndex < episodesData.length - 1) {{
                            setTimeout(() => {{
                                if (currentStepIndex >= ep.trajectory.length - 1) {{
                                    loadEpisode(currentEpIndex + 1);
                                }}
                            }}, 1600);
                        }}
                    }}
                }}
            }}

            updateCamera();
            renderer.render(scene, camera);
        }}
    </script>
</body>
</html>
"""
        return html
