version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: owcl-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: owcl-ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
