"""
src/models/yolo_detector.py
───────────────────────────
YOLOv8 wrapper for training, validation, and inference.

Wraps Ultralytics YOLO with MLflow logging, checkpoint management,
and a clean Python API used by both train_baseline.py and train_continual.py.

Usage:
    from src.models.yolo_detector import YOLODetector

    detector = YOLODetector(model_size="yolov8m", num_classes=4)
    detector.train(dataset_yaml="data/processed/waymo/dataset.yaml", epochs=50)
    results = detector.predict("path/to/image.jpg")
"""

import logging
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Union

import torch
import numpy as np

logger = logging.getLogger(__name__)

try:
    from ultralytics import YOLO
    ULTRALYTICS_AVAILABLE = True
except ImportError:
    ULTRALYTICS_AVAILABLE = False
    logger.warning("ultralytics not found. Install with: pip install ultralytics")

# Lazy MLflow import — avoids NumPy 1.x/2.x crash at module load time
MLFLOW_AVAILABLE = False
def _try_import_mlflow():
    global MLFLOW_AVAILABLE
    try:
        import mlflow  # noqa: F401
        MLFLOW_AVAILABLE = True
        return mlflow
    except Exception:
        return None


class YOLODetector:
    """
    YOLOv8-based object detector.

    Wraps Ultralytics YOLO with:
      - MLflow experiment logging
      - Checkpoint save/load
      - Probability vector extraction (needed for EWC & open-set)
    """

    VALID_SIZES = {"yolov8n", "yolov8s", "yolov8m", "yolov8l", "yolov8x"}

    def __init__(
        self,
        model_size: str = "yolov8m",
        num_classes: int = 4,
        checkpoint: Optional[str] = None,
        device: str = "cuda",
    ):
        assert model_size in self.VALID_SIZES, \
            f"model_size must be one of {self.VALID_SIZES}"

        self.model_size  = model_size
        self.num_classes = num_classes
        self.device      = device if torch.cuda.is_available() else "cpu"

        if not ULTRALYTICS_AVAILABLE:
            logger.error("Ultralytics YOLO not available. Cannot create model.")
            self.model = None
            return

        if checkpoint and Path(checkpoint).exists():
            logger.info(f"Loading checkpoint: {checkpoint}")
            self.model = YOLO(checkpoint)
        else:
            logger.info(f"Initializing pretrained {model_size}")
            self.model = YOLO(f"{model_size}.pt")

    # ── Training ─────────────────────────────────────────────────────────────

    def train(
        self,
        dataset_yaml: str,
        epochs: int = 50,
        batch_size: int = 16,
        img_size: int = 640,
        lr: float = 0.001,
        checkpoint_name: str = "yolo_run",
        mlflow_run_name: Optional[str] = None,
        extra_params: Optional[Dict] = None,
    ) -> Dict:
        """
        Fine-tune YOLOv8 on a YOLO-format dataset.

        Args:
            dataset_yaml: Path to dataset.yaml (generated by loaders).
            epochs: Training epochs.
            batch_size: Batch size per GPU.
            img_size: Input image size (square).
            lr: Initial learning rate.
            checkpoint_name: Run directory name under runs/.
            mlflow_run_name: Optional MLflow run name.
            extra_params: Additional kwargs forwarded to YOLO.train().

        Returns:
            metrics dict with val mAP50, mAP50-95.
        """
        if self.model is None:
            raise RuntimeError("Model not initialized (ultralytics missing?).")

        # NOTE: Ultralytics always appends a task subfolder (e.g. "detect/")
        # to whatever "project" you pass, AND the final save_dir may differ
        # from what we expect (especially with spaces in paths).
        # We therefore let Ultralytics write wherever it wants, then resolve
        # the actual save_dir from the trainer object after training.
        params = {
            "data":     dataset_yaml,
            "epochs":   epochs,
            "batch":    batch_size,
            "imgsz":    img_size,
            "lr0":      lr,
            "device":   self.device,
            "project":  "runs",
            "name":     checkpoint_name,
            "exist_ok": True,
            "verbose":  True,
            **(extra_params or {}),
        }

        mlflow = _try_import_mlflow()
        if mlflow and MLFLOW_AVAILABLE:
            try:
                mlflow.end_run()   # Close any stale active run first
            except Exception:
                pass
            with mlflow.start_run(run_name=mlflow_run_name or checkpoint_name, nested=False):
                mlflow.log_params({
                    "model_size":  self.model_size,
                    "num_classes": self.num_classes,
                    "dataset":     dataset_yaml,
                    **{k: v for k, v in params.items() if k not in ("data", "device")},
                })
                results = self.model.train(**params)
                metrics = self._extract_metrics(results)
                mlflow.log_metrics(metrics)
                best_ckpt = self._resolve_best_ckpt(results, checkpoint_name)
                if best_ckpt and best_ckpt.exists():
                    mlflow.log_artifact(str(best_ckpt), artifact_path="checkpoints")
        else:
            results = self.model.train(**params)
            metrics = self._extract_metrics(results)

        # Always print where the checkpoint actually landed
        best_ckpt = self._resolve_best_ckpt(results, checkpoint_name)
        if best_ckpt:
            logger.info(f"Best checkpoint → {best_ckpt}")
        else:
            logger.warning("Could not locate best checkpoint after training.")

        logger.info(f"Training complete. Metrics: {metrics}")
        return metrics

    @staticmethod
    def _resolve_best_ckpt(results, checkpoint_name: str) -> Optional[Path]:
        """
        Resolve the actual best.pt path from Ultralytics trainer results.

        Ultralytics >= 8.x appends task subfolders (e.g. 'detect/') to the
        project dir, and path resolution can vary across versions. We try
        multiple strategies so the path always resolves correctly regardless
        of Ultralytics version or OS path quirks.
        """
        # Strategy 1: read save_dir directly from the results/trainer object
        for attr in ("save_dir", "trainer"):
            obj = getattr(results, attr, None)
            if obj is not None:
                save_dir = obj if isinstance(obj, Path) else getattr(obj, "save_dir", None)
                if save_dir:
                    candidate = Path(save_dir) / "weights" / "best.pt"
                    if candidate.exists():
                        return candidate

        # Strategy 2: walk from cwd looking for a matching weights/best.pt
        import os
        for root, dirs, files in os.walk("."):
            if "best.pt" in files and "weights" in root:
                # Check the parent folder name matches checkpoint_name
                candidate = Path(root) / "best.pt"
                if checkpoint_name in str(candidate):
                    return candidate

        # Strategy 3: glob search scoped to likely output dirs
        for pattern in [
            f"runs/**/{checkpoint_name}/weights/best.pt",
            f"**/runs/**/{checkpoint_name}/weights/best.pt",
        ]:
            matches = list(Path(".").glob(pattern))
            if matches:
                return sorted(matches)[-1]   # most recent

        return None

    # ── Validation ────────────────────────────────────────────────────────────

    def validate(self, dataset_yaml: str, img_size: int = 640) -> Dict:
        """Run validation and return mAP metrics."""
        if self.model is None:
            raise RuntimeError("Model not initialized.")
        results = self.model.val(data=dataset_yaml, imgsz=img_size, device=self.device)
        return self._extract_metrics(results)

    # ── Inference ─────────────────────────────────────────────────────────────

    def predict(
        self,
        source: Union[str, np.ndarray],
        conf_threshold: float = 0.25,
        iou_threshold:  float = 0.45,
        return_probs:   bool  = False,
    ) -> List[Dict]:
        """
        Run inference on an image or path.

        Args:
            source: Image path, URL, or numpy array (H, W, 3) BGR.
            conf_threshold: Confidence threshold.
            iou_threshold: NMS IoU threshold.
            return_probs: If True, include raw class probability vectors
                          (needed for entropy-based open-set detection).

        Returns:
            List of detection dicts:
                {"box": [x1,y1,x2,y2], "conf": float, "cls": int,
                 "probs": np.ndarray (optional)}
        """
        if self.model is None:
            raise RuntimeError("Model not initialized.")

        results = self.model.predict(
            source=source,
            conf=conf_threshold,
            iou=iou_threshold,
            device=self.device,
            verbose=False,
        )

        detections = []
        for r in results:
            boxes = r.boxes
            if boxes is None:
                continue
            for i, box in enumerate(boxes):
                det = {
                    "box":  box.xyxy[0].cpu().numpy().tolist(),
                    "conf": float(box.conf[0].cpu()),
                    "cls":  int(box.cls[0].cpu()),
                }
                if return_probs and hasattr(r, "probs") and r.probs is not None:
                    det["probs"] = r.probs.data.cpu().numpy()
                detections.append(det)

        return detections

    # ── Checkpoint utilities ──────────────────────────────────────────────────

    def save(self, path: str):
        """Save model weights."""
        if self.model is None:
            raise RuntimeError("Model not initialized.")
        self.model.save(path)
        logger.info(f"Model saved → {path}")

    def load(self, path: str):
        """Load model weights from a checkpoint."""
        if not ULTRALYTICS_AVAILABLE:
            raise RuntimeError("Ultralytics not available.")
        self.model = YOLO(path)
        logger.info(f"Model loaded ← {path}")

    def get_pytorch_model(self) -> torch.nn.Module:
        """Return the underlying PyTorch nn.Module (needed for EWC)."""
        if self.model is None:
            raise RuntimeError("Model not initialized.")
        return self.model.model

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _extract_metrics(results) -> Dict:
        """Extract a clean metrics dict from Ultralytics results object."""
        try:
            return {
                "mAP50":    float(results.results_dict.get("metrics/mAP50(B)",    0.0)),
                "mAP50_95": float(results.results_dict.get("metrics/mAP50-95(B)", 0.0)),
                "precision":float(results.results_dict.get("metrics/precision(B)",0.0)),
                "recall":   float(results.results_dict.get("metrics/recall(B)",   0.0)),
            }
        except Exception:
            return {"mAP50": 0.0, "mAP50_95": 0.0, "precision": 0.0, "recall": 0.0}
